apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quests-tracker-api-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gulcht/lab-setup.git'
    targetRevision: main
    path: example/k8s/quests-tracker-api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: quest-tracker-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
