apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets
  namespace: quest-tracker-app
spec:
  refreshInterval: 5s

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: api-secrets

  dataFrom:
    - extract:
        key: quests-tracker-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: quest-tracker-app
spec:
  refreshInterval: 5s

  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: postgres-secrets

  dataFrom:
    - extract:
        key: postgres-secrets