apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://192.168.1.207:8200/"
      path: "quests-tracker"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-ca-secret
        namespace: default
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "vault-cluster-ss"
          serviceAccountRef:
            name: "vault-backend-sa"
            namespace: "vault"