apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-hosted
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      # Use your own repo, not this one.
      repository: gulcht/quests-tracker 
      # <username>/<repository>
